/* eslint-disable @typescript-eslint/no-explicit-any */
// Generated by https://quicktype.io

export interface FreeDictionaryWord {
  word: string
  phonetic: string
  phonetics: Phonetic[]
  origin: string
  meanings: FDMeaning[]
}

export interface FDMeaning {
  partOfSpeech: string
  definitions: FDDefinition[]
}

export interface FDDefinition {
  definition: string
  example: string
  synonyms: any[]
  antonyms: any[]
}

export interface Phonetic {
  text: string
  audio?: string
}
